service: cicddemo

provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
#  stage: dev
  region: us-west-2

functions:
  crypto_test:
    handler: handler.endpoint
    name: cicddemolambda
    role: ***********
    layers:
      - ************
#plugins:
#  - serverless-python-requirements
#custom:
#  pythonRequirements:
#    dockerizePip: non-linux

